### ISSUE TITLE
I love the plugin so so...much. How can I donate you some money?

### ISSUE THREAD

**Issue by dmitry-mightydevops** [NimbleArchitect/kubectl-ice#11]
:)

**Comment by NimbleArchitect** [comment]
Thank you for the kind words, it means a lot.

if you would like to donate you can buy me a coffee or two via one of the following links:
[https://www.buymeacoffee.com/NimbleArchitect](https://www.buymeacoffee.com/NimbleArchitect)
[https://ko-fi.com/nimblearchitect](https://ko-fi.com/nimblearchitect)

**Comment by dmitry-mightydevops** [comment]
ok done :) hope you have good coffee near by!
