### ISSUE TITLE
init containers always shown

### ISSUE THREAD

**Issue by stfnbstl** [NimbleArchitect/kubectl-ice#13]
Hi there,

### Report 
I installed version `0.2.9` of kubectl ice and the help page says that init containers are omitted in cpu and memory outputs.
But regardless of whether I set the `-i, --include-init` flag or not, init containers are always shown in my output.

### Expected Behavior

Omit init containers in cpu and memory output by default.
See: `-i, --include-init                   include init container(s) in the output, by default init containers are hidden`

### Actual Behavior

I get init containers in my output every time, regardless of the flag.

Description of my pod:
```bash
Init Containers:
  certs:
    Container ID:  <redacted>
    Image:         <redacted>
    Image ID:      <redacted>
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      cp -r /etc/ssl/certs /transfer

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 14 Sep 2022 20:28:19 +0200
      Finished:     Wed, 14 Sep 2022 20:28:19 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  256Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /transfer from transfer (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-abcde (ro)
Containers:
  application:
    Container ID:   <redacted>
    Image:          <redacted>
    Image ID:       <redacted>
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
```

kubectl ice cpu output:
```bash
❯ kubectl ice cpu application-p-0
CONTAINER        USED  REQUEST  LIMIT  %REQ  %LIMIT
certs            0m    100m     100m   -     -
application      7m    200m     500m   3.36  1.34
```

### kubectl ice version
```bash
❯ kubectl-ice -v
kubectl-ice version 0.2.9
```

### Kubernetes Version

1.22.13

**Comment by NimbleArchitect** [comment]
Thanks for pointing this out I somehow missed that. A new release is rolling out v0.2.10 that correctly hides the init containers for cpu and memory views

**Comment by stfnbstl** [comment]
> Thanks for pointing this out I somehow missed that. A new release is rolling out v0.2.10 that correctly hides the init containers for cpu and memory views

Thanks for your fast answer. I upgraded to v0.2.10 and can confirm, that everything works as expected.
