### ISSUE TITLE
kubectl ice cpu - incorrect value (v0.0.9+)

### ISSUE THREAD

**Issue by burningalchemist** [NimbleArchitect/kubectl-ice#2]
Hi,

After the update from v0.0.8 to v0.0.10 the command `kubectl ice cpu` always shows `1000` for requests/limits. 
I had to downgrade to v0.0.8, since v0.0.9 is also having the same issue.

Example:
v0.0.8
```
T  PODNAME                                               CONTAINER                     USED  REQUEST  LIMIT     %REQ  %LIMIT
S  api-redis-master-0                                    api-redis                     16    125m     500m      15.44 -
```

v0.0.9+
```
T  PODNAME                                               CONTAINER                     USED  REQUEST  LIMIT     %REQ  %LIMIT
S  api-redis-master-0                                    api-redis                     16    1000     1000      15.15 -
```

Thanks for the plugin!

Kind regards,
Sergei

**Comment by NimbleArchitect** [comment]
thanks for raising it to me I completely missed that while testing, a fix is on its way

**Comment by NimbleArchitect** [comment]
release 0.0.11 is up and should fix the issue

**Comment by burningalchemist** [comment]
Works as intended, thanks! :+1:
