### ISSUE TITLE
skip type = "I" containers

### ISSUE THREAD

**Issue by dmitry-mightydevops** [NimbleArchitect/kubectl-ice#3]
```
➜ k ice cpu -l "app.kubernetes.io/name in (backend)"    
T  PODNAME                                   CONTAINER      USED  REQUEST  LIMIT  %REQ  %LIMIT
I  protct-backend-v1-5648c9d8df-nx9nd        install        0m    0m       0m     -     -
S  protct-backend-v1-5648c9d8df-nx9nd        backend        72m   0m       1000m  -     7.13
I  protct-celery-beat-v1-6686dfc9df-lw48m    install        0m    0m       0m     -     -
S  protct-celery-beat-v1-6686dfc9df-lw48m    celery-beat    1m    0m       1000m  -     0.02
I  protct-celery-worker-v1-8664579cd5-xhxqk  install        0m    0m       0m     -     -
S  protct-celery-worker-v1-8664579cd5-xhxqk  celery-worker  2m    0m       1000m  -     0.19
I  protct-django-migrations-v1--1-crcb8      install        0m    0m       0m     -     -
S  protct-django-migrations-v1--1-crcb8      migrations     0m    0m       256m   -     -

```

I assume "I" == init container? What is "S" type container?

Also is it possible all init containers and concentrate only on non-terminated containers?

**Comment by NimbleArchitect** [comment]
Yes I is for an init container and S is for a standard or normal container, I believe it's buried somewhere in the documentation.


Regarding your question about the non terminated containers, are you asking for a command line switch that only shows currently running containers?
 or something else as I'm not sure I follow

**Comment by dmitry-mightydevops** [comment]
right, technically speaking I'm less interested in INIT containers if I need to get a picture of what is going on and I-containers just clog the view.

**Comment by dmitry-mightydevops** [comment]
P.S. - great plugin I love it :)

**Comment by NimbleArchitect** [comment]
> right, technically speaking I'm less interested in INIT containers if I need to get a picture of what is going on and I-containers just clog the view.

Ah, ok

So I'll just hide init containers from the output of the mem and cpu commands by default.

Should be easy enough, leave it with me

**Comment by NimbleArchitect** [comment]
update v0.0.16 hides Init containers from the cpu and memory output using -i flag will show them if they are needed
