### ISSUE TITLE
Error: failed to create clientset: no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by amitech** [NimbleArchitect/kubectl-ice#5]
Getting this error for all command line options.

```
$ kubectl-ice status                    
failed to create clientset: no Auth Provider found for name "oidc"
```

I am using -
idp-issuer-url: https://oidc.mydomain.com/

I am able to access k8s cluster with kubectl.

**Comment by NimbleArchitect** [comment]
I don't currently have k8s configured to use oidc so I'm unable to test but...

A quick google suggests that I just need to import an oidc auth module, I have updated the latest release to v0.0.16 could you try the command again and let me know

**Comment by amitech** [comment]
It is working fine with latest version. Thanks 🙂

**Comment by NimbleArchitect** [comment]
thanks for confirming
