### ISSUE TITLE
priority class

### ISSUE THREAD

**Issue by dmitry-mightydevops** [NimbleArchitect/kubectl-ice#6]
it would be nice to include an option to:
- display all pods with priority classes
- display all pods with a specific priority class

```
kubectl get pods --all-namespaces -o custom-columns=NAME:.metadata.name,PRIORITY:.spec.priorityClassName,VALUE:.spec.priority
```

Something like this.

**Comment by NimbleArchitect** [comment]
what would be the use case for this?

Are you talking about using the priority class as a filter when selecting pods to list (a bit like we do with label selectors) or is there another use you had in mind?

**Comment by NimbleArchitect** [comment]
how about something like this:
`
kubectl-ice mem --select "priority=2000000000" -A
kubectl-ice probes --select 'priorityClassName=system-cluster-critical' -A
`
--select tries a direct match against fields in the pod spec output so it's possible that other fields will also work

field names are not case sensitive but the values are i.e. system-cluster-critical needs to be an exact match but pirorityClassName can be all lower case

I'm about to push a new version so let me know if it works

**Comment by dmitry-mightydevops** [comment]
Yes that works!
