### ISSUE TITLE
status: revisualize to enhance UX

### ISSUE THREAD

**Issue by Dentrax** [NimbleArchitect/kubectl-ice#9]
Thanks for such a great tool! I have some feedback about the status command.

---

1. Use Tree Structure

Currently, `status` command prints a big table that is slightly complicated and hard to distinguish. It would be great to list all containers in tree structure, for example:

```
NAMESPACE  NAME                          READY  RUNNING  REASON  AGE
aa         Pod/foo-6f67dcc579-znb55      True   -                10m
aa         └─Container/first-container   -      True
aa         └─Container/second-container  -      True
```

2. Timestamp is too detailed

```
 TIMESTAMP
 2022-06-17 10:34:57 +0300 +03
```

Do we really need to see date/second details? We can create a new flag called `--details` to expand timestamp. Otherwise, just current time is fine: `10:34:57`

3. MESSAGE is really necessary?

I am not sure how we can use `MESSAGE` column since the terminal has limited width. Currently I see all values set to `-`.

Any thougts?

**Comment by NimbleArchitect** [comment]
I agree the status output does look messy, I also like the idea of a tree view, biggest issues are that the sort flag would break the tree view and the table output code would also need a bit of a rewrite to make this possible.

I believe that removing the date will cause confusion but I may be able to remove the time zone info.  I'll have to look into it first though.

the MESSAGE column is populated with the error description when containers fail to start/load, ill have a play with it, I might be worth moving it to the details flag you mentioned

**Comment by NimbleArchitect** [comment]
I have added the --tree flag to the status command so you end up with something like the below, I have also moved the message and timestamp columns to the --details flag

```
$ kubectl-ice status -l app=myapp --tree
NAMESPACE  NAME                      READY  STARTED  RESTARTS  STATE       REASON            AGE
ice        Pod/web-pod               -      -        0         Running     -                 10m
ice        └─Container/app-broken    false  false    6         Waiting     CrashLoopBackOff  -
ice        └─Container/app-watcher   false  false    6         Waiting     CrashLoopBackOff  -
ice        └─Container/myapp         true   true     0         Running     -                 10m
ice        └─InitContainer/app-init  true   -        0         Terminated  Completed         10m
```

**Comment by NimbleArchitect** [comment]
I don't currently pull the extra information needed to be able to display things like that.  Ill add it to the "maybe in the future" list

**Comment by NimbleArchitect** [comment]
this has now been updated
